---
- name: Enable remote connections
  lineinfile:
    path: "{{ syslog_conf_path }}"
    regexp: "{{ item.match }}"
    line: "{{ item.newline }}"
  loop:
    - match: '^#module\(load="im{{ syslog_protocol }}"\)'
      newline: 'module(load="im{{ syslog_protocol }}")'
    - match: '^#input\(type="im{{ syslog_protocol }}" port="514"\)'
      newline: 'input(type="im{{ syslog_protocol }}" port="{{ syslog_port }}")'

- name: Create template
  blockinfile:
    path: "{{ syslog_conf_path }}"
    block: |
      $template byhost,"/var/log/%HOSTNAME%/%syslogseverity-text%.log"
      *.* -?byhost
  notify: Restart rsyslogd

- name: Open firewall port
  firewalld:
    port: "{{ syslog_port }}/{{ syslog_protocol }}"
    state: enabled
    immediate: yes
    permanent: yes
  when: firewall_preconfigured is not defined or firewall_preconfigured is false
  
