---
- name: Create temporary folder for import files
  become_user: "{{ gunicorn_user }}"
  become: true
  ansible.builtin.tempfile:
    state: directory
    suffix: import
  register: import_dir
  tags: never,gateway.import

- name: Copy registration file to server's tmp
  ansible.builtin.copy:
    src: "{{ registration_list_path }}"
    dest: "{{ import_dir.path }}/students.json"
    owner: "{{ gunicorn_user }}"
  when: import_dir.path is defined
  tags: never,gateway.import

- name: Create hosts.json
  template:
    src: templates/hosts.txt.j2
    dest: "{{ import_dir.path }}/hosts.txt"
    mode: "644"
    owner: "{{ gunicorn_user }}"
  tags: never,gateway.import

- name: Import records to gatway
  become_user: "{{ gunicorn_user }}"
  become: true
  community.general.django_manage:
    command: "import_tables --hostfile={{ import_dir.path }}/hosts.txt {{ import_dir.path}}/students.json"
    app_path: "{{ project_path }}/webapp"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  when: import_dir.path is defined
  environment: "{{ django_environment }}"
  tags: never,gateway.import

- name: Clear the temporary folder
  become_user: "{{ gunicorn_user }}"
  become: true
  ansible.builtin.file:
    path: "{{ import_dir.path }}/{{ item.filename }}"
    state: absent
  when: import_dir.path is defined
  with_items:
  - "{{ import_dir.path }}/students.json"
  - "{{ import_dir.path }}/hosts.txt"

- name: Remove the temporary folder
  become_user: "{{ gunicorn_user }}"
  become: true
  ansible.builtin.file:
    path: "{{ import_dir.path }}"
    state: absent
  when: import_dir.path is defined
