---
- name: Create the Gunicorn script file
  ansible.builtin.template: src=gunicorn_start.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=yes
  tags: deploy

- name: Create the application log folder
  ansible.builtin.file:
    path: "{{ application_log_dir }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: "0664"
    state: directory
  changed_when: false

- name: Check for an existing application logfile
  ansible.builtin.stat:
    path: "{{ application_log_file }}"
  register: p

- name: Create (or retain) the application log file
  # Removing until https://github.com/ansible/ansible/issues/45530 gets resolved.
  # ansible.builtin.copy: content=""
  #       dest={{ application_log_file }}
  #       owner={{ gunicorn_user }}
  #       group={{ gunicorn_group }}
  #       mode=0664
  #       force=no
  ansible.builtin.file:
    path: "{{ application_log_file }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0664
    state: '{{ "file" if p.stat.exists else "touch" }}'

- name: Create the maintenance page
  ansible.builtin.template: src=maintenance_off.html
            dest={{ virtualenv_path }}/maintenance_off.html
            mode=0664

- name: Create the virtualenv postactivate script to set environment variables
  ansible.builtin.template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  tags: deploy


