---

- name: Create a local development environment
  become: true
  hosts: development
  vars:
    update_apt_cache: true
    hostname: localhost
    run_manually: true
  vars_files:
    - group_vars/development/vars.yml
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - avahi
    - db
    - rabbitmq
    - web
    - celery
    - checker
    - pychecker
    - geerlingguy.redis
    - local
