---

- name: Provision logservers
  hosts: logservers
  become: true
  become_user: root
  remote_user: "{{ server_user | default(ansible_user) }}"
  vars:
    update_apt_cache: true
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - logserver
