---
- name: Provision monitor server
  hosts: monitor
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
    db_name: grafana
    db_user: grafana
    db_use_ssl: false
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - db
    - prometheus
    - grafana
