---

- ansible.builtin.import_tasks: dbservers.yml

- ansible.builtin.import_tasks: redisservers.yml

- ansible.builtin.import_tasks: rabbitservers.yml

- ansible.builtin.import_tasks: mediaservers.yml

- ansible.builtin.import_tasks: webservers.yml

- ansible.builtin.import_tasks: workers.yml
