---

- name: Provision RabbitMQ broker
  hosts: rabbitmq
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
    ssl_key_usage: ["serverAuth"]
    ssl_user: rabbitmq
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - ca_signed
    - logclient
    - rabbitmq
