---

- name: Provision RabbitMQ broker
  hosts: rabbit
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - rabbitmq
