---

- name: Provision Redis
  hosts: cache_redis, result_redis
  become: true
  become_user: root
  remote_user: "{{ server_user | default(ansible_user) }}"
  vars:
    update_apt_cache: true
    ssl_key_usage: ["serverAuth"]
    ssl_user: redis
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - ca_signed
    - logclient
    - geerlingguy.redis
