---

- ansible.builtin.import_playbook: logservers.yml

- name: Provision standalone base functionality servers
  hosts: lovelace
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - logclient
    - geerlingguy.redis
    - db
    - lovelace
    - gunicorn
    - nginx

- ansible.builtin.import_playbook: gateway.yml
