---

- name: Provision Workers
  hosts: workers
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
    run_django_syncdb: false
    run_django_db_migrations: false
    run_django_collectstatic: false
    ssl_key_usage: ["clientAuth"]
    ssl_user: "{{ worker_username }}"
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - ca_signed
    - logclient
    - lovelace
    - checker
    - pychecker
    - celery
