---

- name: Provision Redis
  hosts: workers
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
    run_django_syncdb: false
    run_django_db_migrations: false
    run_django_collectstatic: false
  module_defaults:
    ansible.builtin.apt:
      force_apt_get: true

  roles:
    - base
    - web
    - checker
    - pychecker
    - celery
