---
- name: Generate host private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_path }}"
    owner: "{{ ssl_user }}"
    mode: "600"

- name: Create certificate signing request (CSR) for self-signed certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ssl_key_path }}"
    common_name: "{{ inventory_hostname }}"
    organization_name: "{{ org_name }}"
    extended_key_usage: "{{ ssl_key_usage }}"
    owner: "{{ ssl_user }}"
  register: csr

- name: Sign the certificate on the CA machine
  community.crypto.x509_certificate_pipe:
    provider: ownca
    csr_content: "{{ csr.csr }}"
    ownca_cert: "{{ ca_crt_path }}"
    ownca_privatekey: "{{ ca_key_path }}"
    ownca_privatekey_passphrase: "{{ ca_passphrase }}"
  delegate_to: "{{ groups.ca_server.0 }}"
  register: csr_result

- name: Save the result
  ansible.builtin.copy:
    dest: "{{ ssl_crt_path }}"
    content: "{{ csr_result.certificate }}"
    owner: "{{ ssl_user }}"
    mode: "600"
  when: csr_result is changed

- name: Copy the CA certificate
  ansible.builtin.synchronize:
    src: "{{ ca_crt_path }}"
    dest: "{{ ca_crt_path }}"
    owner: "{{ ssl_user }}"
    mode: "600"
  delegate_to: "{{ groups.ca_server.0 }}"

