---
application_name: lovelace
gunicorn_num_workers: 2
gunicorn_max_requests: 0
gunicorn_timeout_seconds: 300
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
restart_target: lovelace
gunicorn_log_size: 52428800     # 50 MB
gunicorn_log_backups: 4
gunicorn_loglevel: warn
is_gateway: false
django_use_prometheus: false
