---
application_name: lovelace
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
restart_target: lovelace
gunicorn_log_size: 52428800     # 50 MB
gunicorn_log_backups: 4
gunicorn_loglevel: warn
