---
- name: Create remote.conf
  template:
    src: templates/remote.conf.j2
    dest: "{{ remote_conf_path }}"
    mode: "644"
    owner: root
    group: root
  notify: Restart rsyslogd  
  tags: logclient

- name: Send test message
  syslogger:
    msg: "Connection test message"
    priority: warning
    facility: syslog
  tags: never,logclient.test
