---

- name: Add the controller user to the application group
  ansible.builtin.user: name={{ lookup('ansible.builtin.env', 'USER') }} group={{ gunicorn_group }} state=present
  tags: localdev

- name: Add write privilege to group
  ansible.builtin.file: path={{ project_path }}
        recurse=yes
        mode=g+w
  changed_when: false
  tags: localdev

- name: Change ownership of the repository to controller user
  ansible.builtin.file: path={{ project_path }}
        recurse=yes
        owner={{ lookup('ansible.builtin.env', 'USER') }}
  changed_when: false
  tags: localdev
