---

- name: Add the controller user to the application group
  ansible.builtin.user: name={{ lookup('ansible.builtin.env', 'USER') }} group={{ gunicorn_group }} state=present
  tags: localdev

- name: Add write privilege to group
  ansible.builtin.file: path={{ project_path }}
        recurse=yes
        mode=g+w
  changed_when: false
  tags: localdev

- name: Change ownership of the repository to controller user
  ansible.builtin.file: path={{ project_path }}
        recurse=yes
        owner={{ lookup('ansible.builtin.env', 'USER') }}
  changed_when: false
  tags: localdev

- name: Add write privilege to group for media folder
  ansible.builtin.file: path={{ nginx_media_dir }}
        recurse=yes
        mode=g+w
        state=directory
  changed_when: false
  tags: localdev

- name: Add write privilege to group for static folder
  ansible.builtin.file: path={{ nginx_static_dir }}
        recurse=yes
        mode=g+w
        state=directory
  changed_when: false
  tags: localdev

- name: Add write privilege to group for upload folder
  ansible.builtin.file: path={{ lovelace_private_storage }}
        recurse=yes
        mode=g+w
        state=directory
  changed_when: false
  tags: localdev
