---

- name: Add the RabbitMQ release signing key to the apt trusted keys
  ansible.builtin.apt_key: url=https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
           state=present

- name: Add the RabbitMQ repository to the apt sources list
  ansible.builtin.apt_repository: repo='deb https://deb1.rabbitmq.com/rabbitmq-server/ubuntu/{{ ansible_facts["distribution_release"] }} {{ ansible_facts["distribution_release"] }} main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Add the RabbitMQ Erlang repository to the apt sources list
  ansible.builtin.apt_repository: repo='deb https://deb1.rabbitmq.com/rabbitmq-erlang/ubuntu/{{ ansible_facts["distribution_release"] }} {{ ansible_facts["distribution_release"] }} main'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install RabbitMQ server
  ansible.builtin.apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - rabbitmq-server
  tags:
    - packages

- name: Make sure rabbitmq-server is enabled and running
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true
    # TODO: This is likely due to a bug in Ansible.
    # Remove this line in the future.
    # See https://github.com/ansible/ansible/issues/75005
    use: sysvinit

- name: Enable the RabbitMQ Management Console
  community.rabbitmq.rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

- name: Write extra configuration
  ansible.builtin.template:
    src: templates/rabbitmq.conf.j2
    dest: "{{ rabbitmq_config_path }}"
    mode: "640"
    owner: rabbitmq
    group: rabbitmq
  notify: restart rabbitmq-server

- ansible.builtin.import_tasks: setup_vhosts.yml

- ansible.builtin.import_tasks: setup_users.yml
