---
- name: Install Redis Exporter
  ansible.builtin.apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
    - prometheus-redis-exporter

- name: Write connection settings to override file
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/prometheus-redis-exporter.service.d/override.conf
    mode: "644"
  notify: reload systemd, restart redis exporter

- name: Make sure Redis Exporter is started
  ansible.builtin.service:
    name: prometheus-redis-exporter
    state: started
    enabled: true

# add TLS configuration in the future, presently must be behind nginx if exposed to outside
