---

- name: Ensure that the application file permissions are set properly
  ansible.builtin.file: path={{ virtualenv_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  changed_when: false
