---

# Make sure the sudoers file preserves the ability to use ssh forwarding.
# That way we don't need to store a private key on the server to get
# access to the git repository. Don't forget to add the key used by the
# git repository to your ssh-agent using ssh-add on the machine where you
# run the playbooks.
#
# https://stackoverflow.com/questions/24124140/ssh-agent-forwarding-with-ansible

- name: Add ssh agent line to sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep += "SSH_AUTH_SOCK"
  when: ssh_forward_agent is defined and ssh_forward_agent
  tags: git

- name: Setup the Git repo
  # Specifying user to prevent Git directory ownership warnings, via this SO question:
  # https://stackoverflow.com/a/73356197/2532070
  # The question says this does not work but it does seem to work.
  become_user: "{{ gunicorn_user }}"
  become: true
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    dest: "{{ project_path }}"
    accept_hostkey: true
  when: setup_git_repo is defined and setup_git_repo
  notify: Restart application
  tags: git

- name: Delete all .pyc files
  ansible.builtin.command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ project_path }}"
  tags: git
  changed_when: false
