---

- name: Check if Supervisor exists
  ansible.builtin.stat: path=/etc/init.d/supervisor
  register: supervisor_status
  when: recreate_virtualenv

- name: Ensure all processes managed by Supervisor are stopped if exists
  community.general.supervisorctl:
    name: all
    state: stopped
  when: recreate_virtualenv and supervisor_status.stat.exists

- name: Ensure no existing virtualenv exists
  ansible.builtin.file:
    state: absent
    path: "{{ virtualenv_path }}/"
  when: recreate_virtualenv

- name: Create the virtualenv
  ansible.builtin.command: python3 -m venv {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate

- name: Create the application log folder
  ansible.builtin.file:
    path: "{{ application_log_dir }}"
    owner: "{{ lovelace_user }}"
    group: "{{ lovelace_group }}"
    mode: "0664"
    state: directory
  changed_when: false

- name: Create scripts folder
  ansible.builtin.file:
    path: "{{ virtualenv_scripts_dir }}"
    owner: "{{ lovelace_user }}"
    group: "{{ lovelace_group }}"
    mode: "0755"
    state: directory
  changed_when: false
