---
- name: Create CA private key
  community.crypto.openssl_privatekey:
    path: "{{ ca_key_path }}"
    passphrase: "{{ ca_passphrase }}"
    cipher: auto
    mode: "600"

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ca_key_path }}"
    privatekey_passphrase: "{{ ca_passphrase }}"
    common_name: "{{ ca_cn }}"
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ ca_crt_path }}"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ ca_key_path }}"
    privatekey_passphrase: "{{ ca_passphrase }}"
    provider: selfsigned

