---

- ansible.builtin.import_tasks: create_users_and_groups.yml
  tags: celery

- ansible.builtin.import_tasks: copy_scripts.yml
  tags: celery

- ansible.builtin.import_tasks: setup_supervisor.yml
  tags: celery
  when: run_manually is not defined or run_manually is false
