---
virtualenv_python_version: "{{ base_python_package }}"
base_path: "/opt/{{ application_name }}"
virtualenv_path: "{{ base_path }}/venv"
lovelace_private_storage: "{{ base_path }}/upload"
nginx_static_dir: "{{ www_path }}/static/"
nginx_media_dir: "{{ www_path }}/media/"

# Application settings.
project_path: "{{ base_path }}/{{ project_name }}"
application_log_dir: "{{ base_path }}/logs"
application_log_file: "{{ application_log_dir}}/lovelace.log"
virtualenv_scripts_dir: "{{ virtualenv_path}}/scripts"
dotenv_path: "{{ base_path}}/.env"

gunicorn_user: "{{ application_name }}"

# TODO: create this list by looping through groups['lovelace']
lovelace_main_host: "{{ inventory_hostname }}"
lovelace_main_addr: 127.0.0.1

manage_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DOTENV_PATH: "{{ dotenv_path }}"

# Django environment variables.
lovelace_environment:
  LOVELACE_HOSTNAME: "{{ lovelace_main_host }}"
  LOVELACE_HOSTADDR: "{{ lovelace_main_addr }}"
  LOVELACE_DEFAULT_LANG: "{{ default_lang }}"
  LOVELACE_REDIS_CACHE: "{{ cache_redis }}"
  LOVELACE_WS_CACHE: "{{ ws_redis }}"
  LOVELACE_CELERY_BROKER: "{{ celery_broker }}"
  LOVELACE_CELERY_RESULT: "{{ result_redis }}"
  LOVELACE_SECRET_KEY: "{{ django_secret_key }}"
  LOVELACE_PRIVATE_STORAGE: "{{ lovelace_private_storage }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  LOVELACE_DB_NAME: "{{ db_name }}"
  LOVELACE_DB_USER: "{{ db_user }}"
  LOVELACE_DB_PASS: "{{ db_password }}"
  LOVELACE_DB_HOST: "{{ db_host }}"
  LOVELACE_DB_PORT: "{{ db_port }}"
  LOVELACE_CHECKER_ENV: ' {"PATH": "{{ checking_env_path }}/bin","VIRTUALENV": "{{ checking_env_path }}","LC_CTYPE": "en_US.UTF-8"} '
  LOVELACE_EMAIL_HOST: "{{ django_smtp_host | default('') }}"
  LOVELACE_CELERY_USE_SSL: "{{ '1' if result_redis_ssl else '' }}"
  LOVELACE_CACHE_USE_SSL: "{{ '1' if cache_redis_ssl else '' }}"
  LOVELACE_DB_USE_SSL: "{{ '1' if postgres_use_ssl else '' }}"
  LOVELACE_CLIENT_CA: "{{ ca_crt_path | default('') }}"
  LOVELACE_CLIENT_CERT: "{{ ssl_crt_path | default('') }}"
  LOVELACE_CLIENT_KEY: "{{ ssl_key_path | default('') }}"
  LOVELACE_WS_CACHE_USE_SSL: "{{ '1' if ws_redis_ssl else '' }}"
  LOVELACE_WS_CLIENT_CA: "{{ client_ca_path | default('') }}"
  LOVELACE_WS_CLIENT_CERT: "{{ client_crt_path | default('') }}"
  LOVELACE_WS_CLIENT_KEY: "{{ client_key_path | default('') }}"
  LOVELACE_WS_ORIGINS: "{{ lovelace_main_host }}"
  ENABLE_MANAGEMENT_API: "{{ '1' if use_lovelace_api else '' }}"
  LOVELACE_MANAGEMENT_API_KEY: "{{ lovelace_api_key | default('') }}"
  LOVELACE_PROMETHEUS_EXPORT: "{{ '1' if django_use_prometheus else '' }}"
  LOVELACE_ADMINS: "{{ django_admins | default('') }}"
