---
rabbitmq_server_name: "{{ inventory_hostname }}"
rabbitmq_port: 5672
rabbitmq_api_port: 15672
rabbitmq_api_password: password
rabbitmq_use_ssl: false
rabbitmq_use_letsencrypt: false
rabbitmq_config_path: /etc/rabbitmq/rabbitmq.conf
rabbitmq_ssl_dest_dir: /etc/ssl/
