---

git_repo: https://github.com/lovelace-dev-org/lovelace

project_name: lovelace
application_name: lovelace

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
enable_deadsnakes_ppa: true
virtualenv_python_version: python3.11


# Git settings.
setup_git_repo: true
git_branch: ansible-deploy



# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: "{{ vault_db_password }}"                         # vault
db_host: "{{ groups.postgres.0 }}"                             # read from inventory
{% if hostvars[groups.postgres.0].port is not none %}
  db_port: "{{ hostvars[groups.postgres.0].port }}"              # read from inventory or use default
{% endif %}

# RabbitMQ settings.
rabbitmq_server_name: "{{ groups.rabbitmq.0 }}"        # read from inventory
{% if hostvars[groups.rabbitmq.0].port is not none %}
  rabbitmq_server_port: "{{ hostvars[groups.rabbitmq.0].port }}"
{% endif %}

rabbitmq_admin_user: "{{ vault_rabbitmq_admin_user }}"          # vault
rabbitmq_admin_password: "{{ vault_rabbitmq_admin_password }}"  # vault

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: "{{ vault_rabbitmq_application_password }}"     # vault


result_redis_host: "{{ groups.result_redis.0 }}"                # read from inventory
{% if hostvars[groups.result_redis.0].port is not none %}
  result_redis_port: "{{ hostvars[groups.result_redis.0].port }}"                     # read from inventory
{% else %}
  result_redis_port: 6379
{% endif %}

result_redis_db: "{{ hostvars[groups.result_redis.0].result_db }}"                          # host variable
cache_redis_host: "{{ groups.cache_redis.0 }}"                # read from inventory
{% if hostvars[groups.cache_redis.0].port is not none %}
  cache_redis_port: "{{ hostvars[groups.cache_redis.0].port }}"                     # read from inventory
{% else %}
  cache_redis_port: 6379
{% endif %}
cache_redis_db: "{{ hostvars[groups.cache_redis.0].cache_db }}"                          # host variable

cache_redis: "redis://{{ cache_redis_host }}:{{ cache_redis_port }}/{{ cache_redis_db }}"       # read from inventory + host variable


# Application settings.
django_settings_file: "{{ application_name }}.settings.production"
django_secret_key: "{{ vault_django_secret_key }}"     # vault
django_superuser_name: "{{ vault_django_superuser_name }}"                                                 # vault
django_superuser_pass: "{{ vault_django_superuser_pass }}"                                             # vault
django_superuser_mail: "{{ vault_django_superuser_mail }}"                                          # vault

celery_broker: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@{{ rabbitmq_server_name }}:{{ rabbitmq_server_port }}/{{ rabbitmq_application_vhost }}"

requirements_file: "{{ project_path }}/requirements.txt"

run_django_db_migrations: true
run_django_collectstatic: true


default_lang: en


content_import_list:
- src_folder: ./content
  filename: dev-first-instance_export.zip
  group: DefaultGroup
  responsible: "{{ django_superuser_name }}"

# Nginx settings.
nginx_ssl_crt: "{{ vault_nginx_ssl_crt }}"
nginx_ssl_key: "{{ vault_nginx_ssl_key }}"

