---

git_repo: https://github.com/lovelace-dev-org/lovelace

project_name: lovelace
application_name: lovelace

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
enable_deadsnakes_ppa: true
virtualenv_python_version: python3.11


use_syslog: true
syslog_protocol: tcp

# Git settings.
setup_git_repo: true
git_branch: ansible-deploy

ca_passphrase: "{{ vault_ca_passphrase }}"

syslog_address: "{{ groups.logservers.0 }}"

# Database settings.
remote_db: true
postgres_use_ssl: true
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: "{{ vault_db_password }}"                         # vault
db_host: "{{ groups.dbservers.0 }}"                             # read from inventory
db_port: "{{ hostvars[groups.dbservers.0].port | default(5432) }}"              # read from inventory or use default

# RabbitMQ settings.
rabbitmq_use_ssl: true
rabbitmq_server_name: "{{ groups.rabbitmq.0 }}"        # read from inventory
rabbitmq_server_port: "{{ hostvars[groups.rabbitmq.0].port | default(5672) }}"

rabbitmq_admin_user: "{{ vault_rabbitmq_admin_user }}"          # vault
rabbitmq_admin_password: "{{ vault_rabbitmq_admin_password }}"  # vault

rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: "{{ vault_rabbitmq_application_password }}"     # vault

redis_use_ssl: true
rabbitmq_worker_user: "{{ application_name }}-worker"
rabbitmq_worker_password: "{{ vault_rabbitmq_worker_password }}"

result_redis_host: "{{ groups.result_redis.0 }}"                # read from inventory
result_redis_port: "{{ hostvars[groups.result_redis.0].port | default(6379) }}"                     # read from
redis_bind_interface: "{{ inventory_hostname }}"
result_redis_db: "{{ hostvars[groups.result_redis.0].result_db }}"                          # host variable
cache_redis_host: "{{ groups.cache_redis.0 }}"                # read from inventory
cache_redis_port: "{{ hostvars[groups.cache_redis.0].port | default(6379) }}"                     # read from inventory
cache_redis_db: "{{ hostvars[groups.cache_redis.0].cache_db }}"                          # host variable

cache_redis: "redis{{ 's' if redis_use_ssl }}://{{ cache_redis_host }}:{{ cache_redis_port }}/{{ cache_redis_db }}"       # read from inventory + host variable
result_redis: "redis{{ 's' if redis_use_ssl }}://{{ result_redis_host }}:{{ result_redis_port }}/{{ result_redis_db }}"


redis_extra_config_no_ssl: |
  syslog-enabled yes

redis_extra_config_ssl: |
  syslog-enabled yes
  tls-port {{ hostvars[inventory_hostname].port | default(6379) }}
  tls-cert-file {{ ssl_crt_path }}
  tls-key-file {{ ssl_key_path }}
  tls-ca-cert-file {{ ca_crt_path }}

redis_self_port: "{{ hostvars[inventory_hostname].port | default(6379) }}"
redis_port: "{{ 0 if redis_use_ssl else redis_self_port }}"
redis_extra_config: "{{ redis_extra_config_ssl if redis_use_ssl is true else redis_extra_config_no_ssl }}"

# Application settings.
django_settings_file: "{{ application_name }}.settings.production"
django_secret_key: "{{ vault_django_secret_key }}"     # vault
django_superuser_name: "{{ vault_django_superuser_name }}"                                                 # vault
django_superuser_pass: "{{ vault_django_superuser_pass }}"                                             # vault
django_superuser_mail: "{{ vault_django_superuser_mail }}"                                          # vault

celery_broker: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@{{ rabbitmq_server_name }}:{{ rabbitmq_server_port }}/{{ rabbitmq_application_vhost }}"
worker_celery_broker: "amqp://{{ rabbitmq_worker_user }}:{{ rabbitmq_worker_password }}@{{ rabbitmq_server_name }}:{{ rabbitmq_server_port }}/{{ rabbitmq_application_vhost }}"

admins: "{{ vault_django_admins }}"
requirements_file: "{{ project_path }}/requirements.txt"


run_django_db_migrations: true
run_django_collectstatic: true

use_lovelace_api: false

default_lang: en


content_import_list:
- src_folder: ./content
  filename: dev-first-instance_export.zip
  group: DefaultGroup
  responsible: "{{ django_superuser_name }}"

# Nginx settings.
nginx_ssl_crt: "{{ vault_nginx_ssl_crt }}"
nginx_ssl_key: "{{ vault_nginx_ssl_key }}"

# Monitoring
# Monitoring
monitored_nodes: "{{ groups.all }}"
grafana_admin_name: "{{ vault_grafana_admin_name }}"
grafana_admin_pass: "{{ vault_grafana_admin_pass }}"
grafana_admin_email: "{{ vault_grafana_admin_email }}"
grafana_secret_key: "{{ vault_grafana_secret_key }}"
