---
- name: Install Prometheus
  ansible.builtin.apt:
    update_cache: "{{ update_cache }}"
    state: present
    name:
    - prometheus

- name: Make sure Prometheus is started
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true

- name: Write extra configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"
    mode: "644"
  notify: restart prometheus
