---
- name: Install Prometheus
  ansible.builtin.apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
    - prometheus
  tags: prometheus

- name: Get IP addresses of monitored nodes
  ansible.builtin.setup:
    gather_subset: default_ipv4
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ monitored_nodes }}"
  tags: prometheus

- name: Create password file for Django Prometheus access
  ansible.builtin.lineinfile:
    path: "{{ django_prometheus_pwfile }}"
    line: "{{ prometheus_auth_pass }}"
    create: yes
    owner: root
    group: prometheus
    mode: "640"
  when: django_use_prometheus

- name: Write extra configuration
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"
    mode: "644"
  notify: restart prometheus
  tags: prometheus

- name: Make sure Prometheus is started
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
  tags: prometheus

