---

- ansible.builtin.import_tasks: install_additional_packages.yml
  tags: packages

- ansible.builtin.import_tasks: create_users_and_groups.yml

- ansible.builtin.import_tasks: set_file_permissions.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_virtualenv.yml
  tags: virtualenv

- ansible.builtin.import_tasks: setup_git_repo.yml
  tags: deploy

- ansible.builtin.import_tasks: setup_django_app.yml
  tags: deploy

- ansible.builtin.import_tasks: create_django_superuser.yml

- ansible.builtin.import_tasks: setup_supervisor.yml
  tags: supervisor
  when: run_manually is not defined or run_manually is false

- ansible.builtin.import_tasks: import_content.yml
  tags: [lovelace.import, never]
