---

- name: Install virtualenv
  ansible.builtin.pip:
    name: virtualenv
    version: 20.24.6
  tags: packages

- name: Check if Supervisor exists
  ansible.builtin.stat: path=/etc/init.d/supervisor
  register: supervisor_status
  when: recreate_virtualenv

- name: Ensure all processes managed by Supervisor are stopped if exists
  community.general.supervisorctl:
    name: all
    state: stopped
  when: recreate_virtualenv and supervisor_status.stat.exists

- name: Ensure no existing virtualenv exists
  ansible.builtin.file:
    state: absent
    path: "{{ virtualenv_path }}/"
  when: recreate_virtualenv

- name: Create the virtualenv
  ansible.builtin.command: virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate

- name: Create the application log folder
  ansible.builtin.file:
    path: "{{ application_log_dir }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: "0664"
    state: directory
  changed_when: false

- name: Check for an existing application logfile
  ansible.builtin.stat:
    path: "{{ application_log_file }}"
  register: p

- name: Create the virtualenv postactivate script to set environment variables
  ansible.builtin.template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes
  notify: Restart application
  tags: deploy

