---
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"

lovelace_private_storage: "{{ virtualenv_path }}/upload"
lovelace_pg_passfile: "{{ virtualenv_path }}/.lovelace_pgpass"
lovelace_pg_servicefile: "{{ virtualenv_path }}/.pg_service.conf"

nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"

restart_target: "{{ application_name }}"

# Django environment variables.
lovelace_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SUPERUSER_USERNAME: "{{ django_superuser_name }}"
  DJANGO_SUPERUSER_PASSWORD: "{{ django_superuser_pass }}"
  DJANGO_SUPERUSER_EMAIL: "{{ django_superuser_mail }}"
  LOVELACE_HOSTNAME: "{{ lovelace_main_host }}"
  LOVELACE_HOSTADDR: "{{ lovelace_main_addr }}"
  LOVELACE_DEFAULT_LANG: "{{ default_lang }}"
  LOVELACE_REDIS_CACHE: "{{ cache_redis }}"
  LOVELACE_CELERY_BROKER: "{{ celery_broker }}"
  LOVELACE_CELERY_RESULT: "{{ result_redis }}"
  LOVELACE_SECRET_KEY: "{{ django_secret_key }}"
  LOVELACE_PRIVATE_STORAGE: "{{ lovelace_private_storage }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  LOVELACE_DB_NAME: "{{ db_name }}"
  LOVELACE_DB_USER: "{{ db_user }}"
  LOVELACE_DB_PASS: "{{ db_password }}"
  LOVELACE_DB_HOST: "{{ db_host }}"
  LOVELACE_DB_PORT: "{{ db_port }}"
  LOVELACE_CHECKER_ENV: ' {"PATH": "{{ checking_env_path }}/bin","VIRTUALENV": "{{ checking_env_path }}","LC_CTYPE": "en_US.UTF-8"} '
  LOVELACE_CELERY_USE_SSL: "{{ '1' if rabbitmq_use_ssl else '' }}"
  LOVELACE_CACHE_USE_SSL: "{{ '1' if redis_use_ssl else '' }}"
  LOVELACE_DB_USE_SSL: "{{ '1' if postgres_use_ssl else '' }}"
  LOVELACE_CLIENT_CA: "{{ ca_crt_path | default('') }}"
  LOVELACE_CLIENT_CERT: "{{ ssl_crt_path | default('') }}"
  LOVELACE_CLIENT_KEY: "{{ ssl_key_path | default('') }}"
  ENABLE_MANAGEMENT_API: "{{ '1' if use_lovelace_api else '' }}"
  LOVELACE_MANAGEMENT_API_KEY: "{{ lovelace_api_key | default('') }}"
  LOVELACE_PROMETHEUS_EXPORT: "{{ '1' if django_use_prometheus else '' }}"

gateway_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  GATEWAY_HOSTNAME: "{{ lovelace_main_host }}"
  GATEWAY_HOSTADDR: "{{ lovelace_main_addr }}"
  GATEWAY_SECRET_KEY: "{{ django_secret_key }}"
  GATEWAY_DB_NAME: "{{ db_name }}"
  GATEWAY_DB_USER: "{{ db_user }}"
  GATEWAY_DB_PASS: "{{ db_password }}"
  GATEWAY_DB_HOST: "{{ db_host }}"
  GATEWAY_DB_PORT: "{{ db_port }}"
  GATEWAY_DB_USE_SSL: "{{ '1' if postgres_use_ssl else '' }}"
  GATEWAY_CLIENT_CA: "{{ ca_crt_path | default('') }}"
  GATEWAY_CLIENT_CERT: "{{ ssl_crt_path | default('') }}"
  GATEWAY_CLIENT_KEY: "{{ ssl_key_path | default('') }}"
  GATEWAY_STATIC_ROOT: "{{ nginx_static_dir }}"
  LOVELACE_MANAGEMENT_API_KEY: "{{ lovelace_api_key | default('') }}"

django_environment: "{{ gateway_environment if is_gateway else lovelace_environment }}"
