---
gunicorn_user: "{{ lovelace_user }}"
gunicorn_group: "{{ lovelace_group }}"

gunicorn_log_file: "{{ application_log_dir }}/gunicorn.log"

lovelace_private_storage: "{{ base_path }}/upload"
lovelace_pg_passfile: "{{ base_path }}/.lovelace_pgpass"
lovelace_pg_servicefile: "{{ base_path }}/.pg_service.conf"

nginx_static_dir: "{{ www_path }}/static/"
nginx_media_dir: "{{ www_path }}/media/"

restart_target: "{{ application_name }}"
